TRAILS = {
    "via-francigena": {
        "name": "Via Francigena",
        "description": "Tratto storico che attraversa Albano Laziale e Ariccia verso i Colli Albani",
        "type": "hiking",
        "difficulty": "facile",
        "length_km": 18,
        "surface": "misto (asfalto e sterrato)",
        # Punto medio del tracciato per il meteo
        "weather_lat": 41.730,
        "weather_lon": 12.660,
        "color": "#e74c3c",
        # ID relation OpenStreetMap della Via Francigena nel Lazio
        # Verifica su openstreetmap.org se l'ID è aggiornato
        "osm_relation_id": 3699000,
        "gpx_file": None,
        "tags": ["storico", "escursionismo", "pellegrinaggio"],
        "segnavia": "VF",
    },
    "anello-monte-cavo": {
        "name": "Anello Monte Cavo",
        "description": "Percorso ad anello attorno alla vetta di Monte Cavo (949m), ex sede radar NATO",
        "type": "mtb_hiking",
        "difficulty": "medio",
        "length_km": 14,
        "surface": "sterrato",
        "weather_lat": 41.747,
        "weather_lon": 12.700,
        "color": "#27ae60",
        "osm_relation_id": None,  # Inserire ID OSM se disponibile
        "gpx_file": "static/gpx/anello-monte-cavo.gpx",  # file locale opzionale
        "tags": ["mtb", "escursionismo", "panoramico"],
        "segnavia": "CAI 601",
    },
    "sentiero-maschio-faete": {
        "name": "Sentiero Maschio delle Faete",
        "description": "Traversata verso la vetta più alta dei Castelli Romani (956m) nel cuore del Parco",
        "type": "hiking",
        "difficulty": "medio",
        "length_km": 10,
        "surface": "sentiero",
        "weather_lat": 41.765,
        "weather_lon": 12.715,
        "color": "#8e44ad",
        "osm_relation_id": None,
        "gpx_file": "static/gpx/maschio-faete.gpx",
        "tags": ["escursionismo", "parco", "natura"],
        "segnavia": "CAI 610",
    },
    "via-dei-laghi": {
        "name": "Via dei Laghi",
        "description": "Percorso panoramico che collega il Lago Albano e il Lago di Nemi attraverso i boschi",
        "type": "mtb_hiking",
        "difficulty": "facile",
        "length_km": 22,
        "surface": "strada forestale",
        "weather_lat": 41.750,
        "weather_lon": 12.720,
        "color": "#2980b9",
        "osm_relation_id": None,
        "gpx_file": "static/gpx/via-dei-laghi.gpx",
        "tags": ["mtb", "escursionismo", "laghi", "panoramico"],
        "segnavia": None,
    },
    "artemisio-loop": {
        "name": "Loop Maschio d'Artemisio",
        "description": "Anello tecnico attorno al Maschio d'Artemisio (891m), zona meno frequentata del Parco",
        "type": "mtb",
        "difficulty": "difficile",
        "length_km": 16,
        "surface": "singletracck e sterrato",
        "weather_lat": 41.717,
        "weather_lon": 12.750,
        "color": "#e67e22",
        "osm_relation_id": None,
        "gpx_file": "static/gpx/artemisio-loop.gpx",
        "tags": ["mtb", "tecnico", "singletrack"],
        "segnavia": None,
    },
}
